name: C++ CI 1-st task

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: boost install
      run: sudo apt-get update && sudo apt-get install libboost-test-dev 
    - name: make
      run: |
          cd 1st && mkdir build && cd build
          cmake -DPATCH_VERSION=${{ github.run_number }} ..
          make test_version
          make helloworld_cli
    - name: run tests
      run: cd 1st && cd build && make test
    - name: run hello 
      run: cd 1st && cd build && ./helloworld_cli
