name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: |
          cd 1st && mkdir build && 
          cmake ..
          make test_version
          make helloworld_cli
#     - name: make
#       run: make
#     - name: make test_version
#       run: make test_version
#     - name: make helloworld_cli
#       run: make helloworld_cli
