name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake
    - name: make
      run: make
    - name: make test_version
      run: make test_version
    - name: make helloworld_cli
      run: make helloworld_cli
